### PR TITLE
Accordion component

### LINKED ISSUE #165: accordion component

### PR DESCRIPTION
**Pull request by maxim-dolgovmd**
## PR includes

- [x] Feature

## Related issues

Resolve #165 

## QA Instructions, Screenshots, Recordings
  
Снимок экрана 2024-09-17 в 13 04 48

### CODE REVIEW

**Comment by maxim-dolgovmd** [comment]
canary

**Comment by DenisVorop** [comment]
Canary available: `@plex-inc/bricks@0.0.0-aff881d`

**Comment by DenisVorop** [comment]
Canary available: `@plex-inc/bricks@0.0.0-62909bb`

**Comment by DenisVorop** [comment]
Canary available: `@plex-inc/bricks@0.0.0-2f331d4`

**Review by DenisVorop — APPROVED** [review]

**Pull request merged**
